### ISSUE TITLE
Practical vs. theoretical reproducibility

### ISSUE THREAD

**Issue by azag0** [ReScience/ReScience#11] opened 2015-09-03 20:44 UTC
I see some open questions regarding which research is reproducible and which is not. Here are some hypothetical edge cases:

- My code is platform-specific assembler and can be run only on the blue gene supercomputer.
- My calculations are fully reproducible, but take millions of CPU hours to reproduce.
- My calculations are not deterministic, and I'm not concerned with statistics, but with properties of one particular case (think about measuring/simulating, and studying a single instance of a storm).

In this light, the requirement that all tools must be open source seems questionable to me. As long as one specifies a version or git commit of a proprietary tool, the calculation is in theory perfectly verifiable. I'm not a fan of closed source either, but politics maybe should not play role here? In the end, if someone uses a tool that is proprietary and no one can verify it, the work just won't get reviewed and accepted. So there is a natural incentive for going open source. But I don't see why it should make a work automatically rejected if someone with the same version of the tool can verify it. Thoughts?

**Comment by ctb** [comment] 2015-09-03 20:52
On Thu, Sep 03, 2015 at 01:44:05PM -0700, Jan Hermann wrote:
> I see some open questions regarding which research is reproducible and which is not. Here are some edge cases:
> 
> - My code is platform-specific assembler and can be run only on the blue gene supercomputer.
> - My calculations are fully reproducible, but take millions of CPU hours to reproduce.
> - My calculations are not deterministic, and I'm not concerned with statistics, but with properties of one particular case (think about measuring/simulating, and studying a single instance of a storm).
> 
> In this light, the requirement that all tools must be open source seems questionable to me. As long as one specifies a version or git commit of a proprietary tool, the calculation is in theory perfectly verifiable. Thoughts?

How do we get access to your code when you are no longer available?

How do we have the potential to understand the minute technical details
of what you did (and what approximations you made) without access to the
code?

What happens when we implemented what you said you did in the paper, and
get different results, and you won't give us access to your code?

Just a few thoughts off the top of my head :)

**Comment by azag0** [comment] 2015-09-03 21:06
Of course, all those situations lead to the research being unverifiable and hence should not be published here. But the examples I have written, although being open source, are also practically unverifiable. Or at least (as with proprietary software) verifiable only for a selected group of people. If one makes the rule that a research must be verifiable by everyone practically, that might very well exclude a lot of open source research. If one makes the rule that a research must be verifiable by someone, that allows also for proprietary software. And by proprietary, I don't mean something I have developed and not showed to anyone, but software that is versioned and sold for money.

Or, to complicate the matter in a more realistic way. What if my code is perfectly open source, but runs only on microsoft windows? I understand this is about having as few barriers as possible. But already owning a computer is a barrier that costs money.

**Comment by azag0** [comment] 2015-09-03 21:21
Full disclaimer: a lot of my research is done with such a git-versioned proprietary, sold-for-money software, on whose development I participate.

**Comment by rougier** [comment] 2015-09-04 05:47
One of the problem with sold-for-money software is that we can't verify the code and put a money barrier for a lot of people. That is a problem in the long term. We want to privilege open-source approaches since we think there are already enough tools around, especially the scientific python ecosystem as show by the [Scipy](http://scipy2015.scipy.org/ehome/index.php?eventid=115969&) and [EuroScipy](https://www.euroscipy.org/2015/) conferences for example (but you're free to use any other language).

The whole idea of replication is that you take the original paper and check if you can replicate. If you cannot, then you have to dig into source codes if available, check other papers if available and possible contact original authors. If you manage to replicate, the original paper + the new one should be just enough for anybody to replicate the result, on any machine.

If your code runs only on Windows, editor and reviewers will most certainly ask why it is the case and help your remove such dependency because we cannot allow such situation. Else, your code will be broken with the next windows update.

**Comment by azag0** [comment] 2015-09-04 10:53
Ok, I see the points. I have to admit I was initially confused, I didn't realize there is the original work, the replication and finally the verification by the reviewer. I thought more about publishing original research here, and getting full scientific peer review, but I understand now that's not the primary goal of rescience.

Back to the topic, let me say a couple of words about the field of computational chemistry and material physics. A typical work in these fields takes advantage of some of the big software packages that pretty much everyone in the field knows about. There is [Gaussian](http://gaussian.com) for chemistry, which is managed by a for-profit company, and which many people [actively hate](http://www.bannedbygaussian.org), there are other packages maintained by academics, but still being sold for money, such as [Molpro](http://www.molpro.net) or [Turbomole](http://www.turbomole-gmbh.com). For computational material physics, there is [VASP](https://www.vasp.at). Of course there are open-source alternatives, such as [Quantum Espresso](http://www.quantum-espresso.org/) or [Psi4](http://www.psicode.org) and many others. These programs often implement the same methods and general algorithms, but due to different approximations made, then often produce slightly (or significantly) different results. It is fairly common to have access to these codes (even the commercial ones), as they are often crucial for research. It is close to impossible to write your own versions of these codes as there are often years of development involved. It takes a whole research group and ten years of work to develop a mature software package of this kind.

A typical computational work might present some new code (to be replicated) for a new method or algorithm, but will also use one of the big packages to get some input data for this new code. Here comes the question. If I were to replicate such a paper, I see three options:

1. I get the data obtained by the commercial package and used as input for the new code from the paper from the original author, and put them in the repository as source files. I replicate only the new code.
2. I have access to the commercial code that was used in the original work and I will recalculate the input data for the new code. This is full replication of the original work.
3. I recalculate the input data for the new code with other big software package, but this will probably lead to inaccurate replication.

Which of these options is preferred?

**Comment by rougier** [comment] 2015-09-04 12:13
At this point, it is difficult to answer and it might be a specific decision by the editor for each specific case. 
If the new algorithm need pre-processed data, I would imagine solution 1 or 2 are ok and if you have a access to 3, that would also be interesting for the community to know this will lead to different results.
But I'm not familiar enough (= not at all) with computational chemistry to give you any definitive answer.

However, I'm quite surprised you can obtain significant different results using same methods/algorithms because on the different approximation. Does this means a result obtained with one software cannot be replicated with a different software ? Is it known and accepted by the community ?

**Comment by azag0** [comment] 2015-09-04 13:10
It is well known and accepted. One has to work this fact. Have a look at this [website](https://molmod.ugent.be/deltacodesdft) that compares many well-known and also less known programs. The situation arises because of a trademark between accuracy and efficiency and the fact that a typical computational material science research is at the edge of what is computationally feasible with current hardware. I'm just wrapping a paper on which a collaborator burned hundreds of thousands of CPU hours  (I myself not more than a couple of thousands). This number is still exceptional, but the order of thousands is normal. Of course you can do relevant research without all this, but then your numbers will be probably either rather qualitative than quantitative or will regard rather model than realistic systems.

**Comment by pdebuyl** [comment] 2015-09-07 08:08
Hi,

The FAQ already gives a pointer with the question `Can I submit a paper using proprietary tools such as Matlab ?`. In the case of mixed workflows my first idea would be that between a well defined starting point and end point the full toolset has to be open-source.

The starting point may include reference data that has been generated elsewhere (proprietary tools, experimental results, huge simulations, for instance) but is available publicly under a free license and on a stable archive such as Zenodo.

The specifics would still be handled by the editor in charge if needed. For Gaussian, the license is not stated explicitly on their website and the source-code is not available for download. This clearly does not meet the requirements.

**Comment by rougier** [comment] 2015-09-16 15:58
I closed this issue, feel free to re-open it if you have further questions on this topic.

**Closed by rougier** 2015-09-16 15:58 UTC
Labels: Question

**Comment by alex-louvet** [comment] 2021-02-23 06:44
I am especially interested in the answer to the situation

> My calculations are fully reproducible, but take millions of CPU hours to reproduce.

I have been working on reproducing some work and got a fully functional code for the reporoduction. However I highly underestimated the computing power requirements needed to fully replicate the original work and I don't have access to such power.

What is the publication policy regarding that matter?

**Comment by rougier** [comment] 2021-03-01 07:39
Can you open a new issue with possibly some details about your work?

**Comment by alex-louvet** [comment] 2021-03-01 07:48
I am working on maybe finding a way to at least partially replicate the experiment. I'll open the issue when I'll have fully determined whether or not I'll be able to do that. Anyways, thank you for the answer

**Comment by rougier** [comment] 2021-03-01 08:22
Ok, but feel free to open a new isuer. We actually do not have a lcear answer and your issue might be the opportunity to decide on how to handle such case (this initial issue is 6 years old and might need some refresh on recommendation)
