### ISSUE TITLE
Original author as a co-author of the replication

### ISSUE THREAD

**Issue by CoraliePicoche** [ReScience/ReScience#101] opened 2021-04-01 09:48 UTC
Dear Editors,

We are currently replicating an article containing both an analytical study of a partial differential equation and computer simulations of an agent-based model. We were able to replicate agent-based simulations on our own. However, for the partial differential equation in the original paper (1 line), neither the derivation nor the solutions were given, while they actually rely on ~ 10 pages of maths, including equations not made explicit in the original paper and not truly available elsewhere. We therefore had to ask the first author how to derive the equations and find their solutions, something in which he invested significant amounts of time. His contribution was essential to the full replication of the paper: in this context, is it possible to have him as a co-author? We can simply acknowledge his contributions, but it may be desirable, if possible of course, to at least propose to him to be a co-author (that is what we would naturally do for any other paper when somebody provides this level of help). 

Thank you in advance for your feedback,

**Comment by rougier** [comment] 2021-04-01 10:37
Since he significantly contributed to the replication, I do not see any reason to exclude him (provided you give some explanation in the paper). @khinsen @oliviaguest @benoit-girard Thought?

**Comment by khinsen** [comment] 2021-04-01 16:22
The issue is the condition "you cannot submit the replication of your own research, nor the research of your close collaborators" in our [author guidelines](https://rescience.github.io/write/), so the question is basically if we still consider them important as initially written (before ReScience C started operation).

The goal of that clause was to ensure independent replication, but perhaps we were a bit too strict. In the present case as described above, the replication is independent, but the original author suppliied missing information. This is definitely something we should encourage.

So I'd say we should (1) accept this submission and (2) think hard about a better formulation of our author guidelines.

**Comment by oliviaguest** [comment] 2021-04-10 14:29
Do we currently ask for CRediT author statements? E.g., see: https://onlinelibrary.wiley.com/doi/abs/10.1002/leap.1210

**Comment by oliviaguest** [comment] 2021-04-10 15:07
Oh, and: https://github.com/all-contributors/all-contributors

**Comment by labarba** [comment] 2021-04-10 15:08
What was the rationale for excluding replication studies that involve the original authors or their collaborators? I can think of no academic integrity concern arising from that situation. It seems to be equating a replication to a peer review, or something like that. Why?

I have one article with a PhD student that replicates previous results of another PhD student in my group (so I'm co-author in both works), and frankly it was hard enough!

- Mesnard, O. and Barba, L.A., 2017. Reproducible and replicable computational fluid dynamics: it’s harder than you think. Computing in Science & Engineering, 19(4), pp.44-55. https://doi.org/10.1109/MCSE.2017.3151254

The key is transparency: if all materials are open, the replication was conducted with full transparency, and the result is reproducible, then it should be fine to intersect author sets, IMO.

**Comment by rougier** [comment] 2021-04-10 17:48
The main reason was to avoid genuine errors to be replicated. If, for example,  you commit an error in the original code, chances are that during the replication, you might commit the same error even if the language is different (for example, wrong integration method because of some conditions). In such case, having a new pair of eyes might help. New pair means this can be the original author provided code is old. But this really depends on the domain

The other reason was to avoid the case of an author that submit a paper to a journal without code and then publish the code in ReScience . We had the case but I don't remember if it was via issue or mail.

In the present case, I think there's no problem having the original author associated.

**Comment by rougier** [comment] 2021-04-10 17:51
@oliviaguest Not at all, but I wonder how we could use it for a replication or repdroduction.

**Comment by oliviaguest** [comment] 2021-04-10 18:53
It's useful in the case of people having divergent contributions/roles for these things to be noted explicitly. Like so-and-so did the coding, and such-and-such did the writing of the documentation, and we all wrote the paper, etc. Get me? Because then you can easily spot if so-and-so did the coding in both projects/versions of the model/codebase, etc?

**Comment by rougier** [comment] 2021-04-11 06:27
Yes, we can introduce that. In fact, for some JOSS review, when I see an author without commits, I generally ask first author what did he.she do in the work.

**Comment by CoraliePicoche** [comment] 2021-04-16 10:05
Thank you very much for all your answers, this was really helpful.
We will keep in mind that we can have our colleague as a co-author, and give the details of the contributions of everyone.

**Comment by rougier** [comment] 2021-04-16 12:46
@CoraliePicoche Perfect. I close the issue then, feel free to re-open if needed.

**Closed as completed by rougier** 2021-04-16 12:46 UTC
